### ISSUE TITLE
not recognizing application.yml, interface error

### ISSUE THREAD

**Issue by anborg** [chrisgleissner/microprofile-config-jasypt#5]
My properties were in 

config/application.yml - recognized by quarkus system, but not this jasypt.

```log
 WARN  [co.gi.ch.co.mi.ja.JasyptConfigSource] (main) Could not read properties from any file in [classpath:application.properties, config/application.properties]
2021-12-20 12:54:03 ERROR [io.qu.de.de.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.AbstractMethodError: Receiver class com.github.chrisgleissner.config.microprofile.jasypt.JasyptConfigSource does not define or inherit an implementation of the resolved method 'abstract java.util.Set getPropertyNames()' of interface org.eclipse.microprofile.config.spi.ConfigSource.
        at io.smallrye.config.ConfigValueConfigSourceWrapper.getPropertyNames(ConfigValueConfigSourceWrapper.java:53)
        at io.smallrye.config.SmallRyeConfigSourceInterceptor.iterateNames(SmallRyeConfigSourceInterceptor.java:38)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.SmallRyeConfigSourceInterceptor.iterateNames(SmallRyeConfigSourceInterceptor.java:34)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.SmallRyeConfigSourceInterceptor.iterateNames(SmallRyeConfigSourceInterceptor.java:34)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.ConfigSourceInterceptor.iterateNames(ConfigSourceInterceptor.java:58)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.ConfigSourceInterceptor.iterateNames(ConfigSourceInterceptor.java:58)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.ProfileConfigSourceInterceptor.iterateNames(ProfileConfigSourceInterceptor.java:86)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.ConfigSourceInterceptor.iterateNames(ConfigSourceInterceptor.java:58)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.quarkus.smallrye.openapi.deployment.OpenApiConfigMapping.iterateNames(OpenApiConfigMapping.java:43)
        at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.iterateNames(SmallRyeConfigSourceInterceptorContext.java:25)
        at io.smallrye.config.SmallRyeConfig$ConfigSources.createPropertyNamesInterceptor(SmallRyeConfig.java:685)
        at io.smallrye.config.SmallRyeConfig$ConfigSources.<init>(SmallRyeConfig.java:551)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:68)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:402)
        at io.quarkus.runtime.configuration.QuarkusConfigFactory.getConfigFor(QuarkusConfigFactory.java:36)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:172)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:416)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:276)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:67)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:92)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:441)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:65)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:137)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)

```

**Comment by chrisgleissner** [comment]
Hello,

Which version of Quarkus and Jasypt are you using?

Thanks
Christian

**Comment by chrisgleissner** [comment]
Hi,

microprofile-config-jasypt depends on MicroProfile Config 1.x. Have a look
at its pom.xml for details.

The error you reported is caused by something on your classpath, presumably
Quarkus itself, pulling in version 2.x of MicroProfile Config framework
which introduced an incompatible change.

Fixing this will most likely require a new release of this library. I will
see when I find the time to do that, but pull requests are always welcome.
:)

Thanks
Christian
